apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webdav
  name: webdav
spec:
  containers:
  - image: rclone/rclone:1.62.2
    name: rclone
    volumeMounts:
    - mountPath: /temp/conf
      name: config
    - mountPath: /config/rclone
      name: config-dir
    - mountPath: /data/webDAV
      name: data
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "cp /temp/conf/rclone.conf /config/rclone/rclone.conf; rclone config password logs pass=$WEBDAV_PASSWORD; while true; rclone copy logs: /data/webDAV; do sleep 5m; done;" ]
    env: 
    - name: WEBDAV_PASSWORD
      valueFrom:
        secretKeyRef:
          name: webdavpwd
          key: password
    resources: {}
  - name: filebeat-sidecar
    image: docker.elastic.co/beats/filebeat:7.5.0
    volumeMounts:
      - name: data
        mountPath: var/log/webdav/
      - name: filebeat-config
        mountPath: /usr/share/filebeat/filebeat.yml
        subPath: filebeat.yml
  volumes: 
  - name: config
    secret:
      optional: false
      secretName: rclone-config
  - name: config-dir
    emptyDir: {}
  - name: data
    emptyDir: {}
  - name: filebeat-config
    configMap:
        name: filebeat-configmap
        items:
          - key: filebeat.yml
            path: filebeat.yml
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
