apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elastic-sc
provisioner: kubernetes.io/no-provisioneri
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
