apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-configmap
data:
  filebeat.yml: |
    logging.level: info
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/webdav/*.*
        - /var/log/webdav/*/*.*

    output.logstash:
      hosts: ['logstash-service:5044']
